// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_content_delivery_bucket": "serverlessreactapp-20181203221726--hostingbucket",
    "aws_content_delivery_bucket_region": "ap-southeast-2",
    "aws_content_delivery_url": "http://serverlessreactapp-20181203221726--hostingbucket.s3-website-ap-southeast-2.amazonaws.com"
};


export default awsmobile;
